module_name: OnPay
compatible_versions: 1.0.8+
author: OnPay
category: payment
tags:
  - on
  - pay
  - on-pay
  - onpay
  - onpay.io
  - payment module
description_short: Payment module that allows your shop to accept payments through OnPay
description: description.md
images:
  - image-1.png
  - image-2.png
  - image-3.png
license: MIT
php_version:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
